- name: Update Ubuntu 20.04 VMs
  hosts: all

  tasks:

  - name: Update system (after refreshing caches)
    become: yes
    become_method: sudo
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 600
      upgrade: yes
      autoremove: true
    register: result

  - name: Check if Reboot Needed
    register: reboot_required_file
    stat:
      path: /var/run/reboot-required
      get_md5: no
      
  - name: Reboot server since kernel was updated 
    when: reboot_required_file.stat.exists
    reboot:
      msg: "Rebooting for kernel updates"
      args:
        removes: /var/run/reboot-required
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
